"""Add color column to networks

Revision ID: 0078ea5d267f
Revises: f67c3aff9114
Create Date: 2024-12-18 10:56:45.771722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0078ea5d267f'
down_revision = 'f67c3aff9114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_column('rit_port_number')
        batch_op.drop_column('network')

    with op.batch_alter_table('networks', schema=None) as batch_op:
        # הוספת העמודה עם ערך ברירת מחדל
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=False, server_default='#FFFFFF'))
        # הסרת ברירת המחדל לאחר הוספת העמודה
        batch_op.alter_column('color', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rit_port_number', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
