"""Add color column to networks

Revision ID: 0078ea5d267f
Revises: f67c3aff9114
Create Date: 2024-12-18 10:56:45.771722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0078ea5d267f'
down_revision = 'f67c3aff9114'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        # הוספת עמודת 'rit_port_number' עם ערך ברירת מחדל
        batch_op.add_column(sa.Column('rit_port_number', sa.Integer(), server_default='0', nullable=True))
        # הוספת עמודת 'network' עם ערך ברירת מחדל
        batch_op.add_column(sa.Column('network', sa.String(length=100), server_default='DefaultNetwork', nullable=False))
        # הסרת ברירת המחדל לאחר הוספה
        batch_op.alter_column('network', server_default=None)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rit_port_number', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
