
"""Add foreign key model_id to routers

Revision ID: 2456f0943a24
Revises: b38d9fa21bbe
Create Date: 2024-12-29 10:47:14

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2456f0943a24'
down_revision = 'b38d9fa21bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('routers_model_id_fkey', type_='foreignkey')
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('routers_model_id_fkey', 'router_models', ['model_id'], ['id'])
        batch_op.drop_column('model')

    # ### end Alembic commands ###

