
"""Fix2 Router and RouterModel relationships

Revision ID: 82d3913f9708
Revises: b71dfd21eecd
Create Date: 2024-12-29 11:29:14

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d3913f9708'
down_revision = 'b71dfd21eecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###

