"""2Fix backref conflict and adjust fields

Revision ID: a6309adccbc1
Revises: fe06e79c2b60
Create Date: 2024-12-31 14:36:42

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6309adccbc1'
down_revision = 'fe06e79c2b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.alter_column('point_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('destination_room',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('connected_port_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('network_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)  # שינוי ל-nullable
        batch_op.drop_column('floor')  # הסרת עמודת floor
        batch_op.drop_column('building')  # הסרת עמודת building

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', sa.String(length=255), nullable=True))  # הוספת עמודת building
        batch_op.add_column(sa.Column('floor', sa.Integer(), nullable=True))  # הוספת עמודת floor
        batch_op.alter_column('network_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)  # החזרת NOT NULL במידת הצורך
        batch_op.alter_column('connected_port_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('destination_room',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('point_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
