
"""Add model_id column to routers

Revision ID: b38d9fa21bbe
Revises: 647b4b8ed6fd
Create Date: 2024-12-26 15:38:30

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38d9fa21bbe'
down_revision = '647b4b8ed6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.drop_constraint('routers_model_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'router_models', ['model_id'], ['id'])
        batch_op.drop_column('model')

    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.drop_constraint('switches_router_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'routers', ['router_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('switches_router_id_fkey', 'routers', ['router_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('routers_model_fkey', 'router_models', ['model'], ['model_name'])

    # ### end Alembic commands ###

