"""Initial migration

Revision ID: d7f2ca333a7a
Revises: 
Create Date: 2024-12-09 12:49:46.412518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7f2ca333a7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('technician_name', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('networks')

    # טיפול בעמודת router_id
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.alter_column('router_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('endpoints_router_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'routers', ['router_id'], ['id'])
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.drop_column('network')
        batch_op.add_column(
            sa.Column(
                'network_type',
                postgresql.ENUM(
                    'שביל החלב', 'נתיב רקיע', 'ממד"ס', 'קליקנט', 'למדן',
                    'רומ"ח', 'רואי', 'ארמי', 'לב', 'ארמי TS', 'אליס',
                    name='network_type_enum'
                ),
                nullable=True
            )
        )

    # עדכון הערכים לברירת מחדל
    op.execute("UPDATE routers SET network_type = 'שביל החלב' WHERE network_type IS NULL")

    # הפיכת העמודה ל-not null
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.alter_column('network_type', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('building',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('North', 'South', 'Pit', name='building_type'),
               existing_nullable=False)
        batch_op.drop_column('network_type')

    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('endpoints_router_id_fkey', 'routers', ['router_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('router_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('networks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='networks_pkey')
    )
    op.drop_table('logs')
    # ### end Alembic commands ###
