"""Update models for Network, Router, Endpoint, and Log

Revision ID: f67c3aff9114
Revises: eb4acaf6af91
Create Date: 2024-12-16 16:04:54.542152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67c3aff9114'
down_revision = 'eb4acaf6af91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('rit_port_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('connected_port_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('point_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('destination_room',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.alter_column('destination_room',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('point_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('connected_port_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('rit_port_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
