"""Add rit_port_number and network columns to Endpoint

Revision ID: fe3ad1b09f21
Revises: 0078ea5d267f
Create Date: 2024-12-19 12:28:55.710854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3ad1b09f21'
down_revision = '0078ea5d267f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rit_port_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('network', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_column('network')
        batch_op.drop_column('rit_port_number')

    # ### end Alembic commands ###
